name: flutter_unity_example
description: Demonstrates how to use the flutter_unity plugin.
publish_to: "none"

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_unity: ^0.2.1+4

flutter:
  uses-material-design: true
